### ISSUE TITLE
dapckage_deb.sh needs to alter the user in the deb files

### ISSUE THREAD

**Issue by aatchison** [MycroftAI/mycroft-wifi-setup#1]
`sudo dpkg -i dist/mycroft-wifi-setup_0.1.0_armhf.deb 
Selecting previously unselected package mycroft-wifi-setup.
(Reading database ... 47193 files and directories currently installed.)
Preparing to unpack .../mycroft-wifi-setup_0.1.0_armhf.deb ...
Unpacking mycroft-wifi-setup (0.1.0) ...
Setting up mycroft-wifi-setup (0.1.0) ...
Initializing init script for mycroft-wifi-setup-client
chown: invalid user: ‘%%INSTALL_USER%%’
Starting Mycroft service mycroft-wifi-setup-client
Processing triggers for systemd (215-17+deb8u7) 
`

**Comment by MatthewScholefield** [comment]
Fixed
