### ISSUE TITLE
Cloning the entire mycroft-core takes up too much space on a small build machine with other jobs

### ISSUE THREAD

**Issue by aatchison** [MycroftAI/mycroft-wifi-setup#3]
This could potentially break things.

**Comment by MatthewScholefield** [comment]
Since it only clones to depth 1 and a single branch, it only takes 24 MB. How small do we want it to get? Either way though, we should still for sure make wifi setup not depend on mycroft-core at all.

**Comment by MatthewScholefield** [comment]
Solved with refactor.
