### ISSUE TITLE
Mark 1 does not support Channels 12 or 13 on 2.4GHz spectrum

### ISSUE THREAD

**Issue by KathyReid** [MycroftAI/mycroft-wifi-setup#31]
### Background

This issue was identified on the [Mycroft Community Forum](https://community.mycroft.ai/t/bug-confirmed-mycroft-mark-i-and-wifi-eu-germany-mark-1-cannot-connect-to-channels-12-or-13/3798/3), I simply validated it. 

Issue was validated on two x Mark 1s running `18.2.6b`, build: 

```
pi@mark_1:/var/log $ apt list | grep mycroft
mycroft-core/unknown,now 18.2.6 armhf [installed,automatic]
mycroft-mark-1/unknown,now 18.2.6 armhf [installed]
mycroft-picroft/unknown 18.2.6 armhf
mycroft-wifi-setup/unknown,now 0.2.5 armhf [installed,aut
```
Router: Netgear DGND3700v2

### Description of issue in object deviation format

If the user's wireless SSID is configured to use either Channel 12 or Channel 13, then the Mark 1 Device will not be able to connect to the channel. 

This was validated using the following sequence: 

* Starting state: My 2.4 GHz wireless SSID is set by default to Auto, which defaults to channel 1. Mark 1 units all happy and responding OK.
* Change wireless SSID to channel 12 manually -> both Mark 1s complain they cannot connect to internet, but all other internet services I have are working.
* Change wireless SSID to channel Auto -> defaults to 1 -> both Mark 1s come back online
* Change wireless SSID to channel 13 manually -> both Mark 1s complain they cannot connect to internet, but all other internet services I have are working.
* Change wireless SSID to channel Auto -> defaults to 1 -> both Mark 1s come back online

### Suspected cause

In the USA, Channels 12 and 13, running frequencies 2467MHz and 2472MHz respectively, are restricted. Hardware manufactured in the USA often does not support these frequencies. However, international countries router configurations _allow_ these frequencies, so it's possible that a router is configured to broadcast an SSID on these frequencies. In that case, Mark 1 cannot connect. 

### Workaround

The only available workaround is to set the router to a different channel/frequency.

**Comment by forslund** [comment]
Interesting find! Seems like the region on the Mark-1 is set to 

Can you check the output of

`sudo iwlist wlan0 frequency` and see if it lists the channels or not my devices seem to using different country settings (one's set to GB and one's set to DE) (`sudo iw reg get` to check that)

My devices list the frequencies atleast, but I've not been able to set my router to either of the channels in question to test.

**Comment by KathyReid** [comment]
Sure!

```
pi@mark_1:~ $ sudo iwlist wlan0 frequency
wlan0     11 channels in total; available frequencies :
          Channel 01 : 2.412 GHz
          Channel 02 : 2.417 GHz
          Channel 03 : 2.422 GHz
          Channel 04 : 2.427 GHz
          Channel 05 : 2.432 GHz
          Channel 06 : 2.437 GHz
          Channel 07 : 2.442 GHz
          Channel 08 : 2.447 GHz
          Channel 09 : 2.452 GHz
          Channel 10 : 2.457 GHz
          Channel 11 : 2.462 GHz
          Current Frequency:2.462 GHz (Channel 11)
```
```
pi@mark_1:~ $ sudo iw reg get
country 00: DFS-UNSET
	(2402 - 2472 @ 40), (N/A, 20), (N/A)
	(2457 - 2482 @ 20), (N/A, 20), (N/A), NO-IR
	(2474 - 2494 @ 20), (N/A, 20), (N/A), NO-OFDM, NO-IR
	(5170 - 5250 @ 80), (N/A, 20), (N/A), NO-IR
	(5250 - 5330 @ 80), (N/A, 20), (0 ms), DFS, NO-IR
	(5490 - 5730 @ 160), (N/A, 20), (0 ms), DFS, NO-IR
	(5735 - 5835 @ 80), (N/A, 20), (N/A), NO-IR
	(57240 - 63720 @ 2160), (N/A, 0), (N/A
```

**Comment by forslund** [comment]
That's quite interesting, this is mine:

```
pi@mark_1:~ $ iwlist wlan0 frequency
wlan0     13 channels in total; available frequencies :
          Channel 01 : 2.412 GHz
          Channel 02 : 2.417 GHz
          Channel 03 : 2.422 GHz
          Channel 04 : 2.427 GHz
          Channel 05 : 2.432 GHz
          Channel 06 : 2.437 GHz
          Channel 07 : 2.442 GHz
          Channel 08 : 2.447 GHz
          Channel 09 : 2.452 GHz
          Channel 10 : 2.457 GHz
          Channel 11 : 2.462 GHz
          Channel 12 : 2.467 GHz
          Channel 13 : 2.472 GHz
          Current Frequency:2.452 GHz (Channel 9)

pi@mark_1:~ $ sudo iw reg get
country DE: DFS-ETSI
        (2400 - 2483 @ 40), (N/A, 20), (N/A)
        (5150 - 5250 @ 80), (N/A, 20), (N/A), NO-OUTDOOR
        (5250 - 5350 @ 80), (N/A, 20), (0 ms), NO-OUTDOOR, DFS
        (5470 - 5725 @ 160), (N/A, 26), (0 ms), DFS
        (5725 - 5875 @ 80), (N/A, 13), (N/A)
        (57000 - 66000 @ 2160), (N/A, 40), (N/A)
```

can you try to run `sudo iw reg set DE` and then reboot and see if the channels update?

**Comment by forslund** [comment]
Correction, that command doesn't survive reboot, and seem to be a little wonky to get working...

Setting REGDOMAIN=DE in /etc/default/crda should work but for me it's not really doing anything...

**Comment by KathyReid** [comment]
```
pi@mark_1:~ $ sudo iw reg get
country 00: DFS-UNSET
	(2402 - 2472 @ 40), (N/A, 20), (N/A)
	(2457 - 2482 @ 20), (N/A, 20), (N/A), NO-IR
	(2474 - 2494 @ 20), (N/A, 20), (N/A), NO-OFDM, NO-IR
	(5170 - 5250 @ 80), (N/A, 20), (N/A), NO-IR
	(5250 - 5330 @ 80), (N/A, 20), (0 ms), DFS, NO-IR
	(5490 - 5730 @ 160), (N/A, 20), (0 ms), DFS, NO-IR
	(5735 - 5835 @ 80), (N/A, 20), (N/A), NO-IR
	(57240 - 63720 @ 2160), (N/A, 0), (N/A)
pi@mark_1:~ $ sudo iw reg set DE
pi@mark_1:~ $ sudo iw reg get
country DE: DFS-ETSI
	(2400 - 2483 @ 40), (N/A, 20), (N/A)
	(5150 - 5250 @ 80), (N/A, 20), (N/A), NO-OUTDOOR
	(5250 - 5350 @ 80), (N/A, 20), (0 ms), NO-OUTDOOR, DFS
	(5470 - 5725 @ 160), (N/A, 26), (0 ms), DFS
	(5725 - 5875 @ 80), (N/A, 13), (N/A)
	(57000 - 66000 @ 2160), (N/A, 40), (N/A)
pi@mark_1:~ $ sudo iwlist wlan0 frequency
wlan0     13 channels in total; available frequencies :
          Channel 01 : 2.412 GHz
          Channel 02 : 2.417 GHz
          Channel 03 : 2.422 GHz
          Channel 04 : 2.427 GHz
          Channel 05 : 2.432 GHz
          Channel 06 : 2.437 GHz
          Channel 07 : 2.442 GHz
          Channel 08 : 2.447 GHz
          Channel 09 : 2.452 GHz
          Channel 10 : 2.457 GHz
          Channel 11 : 2.462 GHz
          Channel 12 : 2.467 GHz
          Channel 13 : 2.472 GHz
          Current Frequency:2.462 GHz (Channel 11)
```

**Comment by KathyReid** [comment]
At the least we've proven though that this **could** be an issue for international Mycroft users. I've updated the Picroft and Mark 1 WiFi documentation with a note to mention this.

**Comment by penrods** [comment]
There is discussion here:
https://www.raspberrypi.org/forums/viewtopic.php?t=36961

Channels 12 and higher are restricted in the US and Raspbian doesn't support it by default.  Manual workarounds are detailed in that article if anyone wants to experiment.

Closing this issue, as we won't be shipping any that are configured this way by default.
